In [7]:
import numpy as np

In [8]:
data = np.random.rand(2, 3, 4)
zeroes = np.zeros((2, 2, 2))
full = np.full((2, 2, 2), 7)
ones = np.ones((2, 2, 2))

In [9]:
data

array([[[0.0878162 , 0.86601353, 0.54729465, 0.90737194],
        [0.47781666, 0.85206039, 0.10925992, 0.02745276],
        [0.77755713, 0.0191249 , 0.82907258, 0.40342299]],

       [[0.77901071, 0.2538194 , 0.76743541, 0.70292923],
        [0.11290255, 0.73933179, 0.33463439, 0.36729466],
        [0.40398917, 0.38927956, 0.14102667, 0.64408237]]])

In [10]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [ ]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
arr = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
shape = data.shape
types = data.dtype
size = data.size

In [ ]:
types

dtype('float64')

In [ ]:
arr = data[0]
slicer = data[0:2]
reverse = data[-1]
single_value = data[0][0][0]

In [ ]:
slicer

array([[[0.91252289, 0.84108703, 0.57262228, 0.08775099],
        [0.34751359, 0.85094488, 0.97986847, 0.55345027],
        [0.42754004, 0.24421018, 0.13275618, 0.15571726]],

       [[0.86624397, 0.59446872, 0.60709032, 0.18110149],
        [0.60256171, 0.80085945, 0.59991867, 0.52314822],
        [0.31467456, 0.31614001, 0.63714265, 0.53016624]]])

In [ ]:
reverse

array([[0.86624397, 0.59446872, 0.60709032, 0.18110149],
       [0.60256171, 0.80085945, 0.59991867, 0.52314822],
       [0.31467456, 0.31614001, 0.63714265, 0.53016624]])

In [ ]:
single_value

0.9125228897944582

In [ ]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [ ]:
list1

array([0.79570925, 0.61421872, 0.78599045, 0.73129087, 0.62499507,
       0.68320856, 0.68601141, 0.01321377, 0.68472952, 0.5776728 ])

In [ ]:
list2

array([0.39969889, 0.94682023, 0.85122499, 0.36149327, 0.96603905,
       0.52512832, 0.426348  , 0.37072569, 0.98958041, 0.77834453])

In [ ]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [ ]:
add

array([1.19540814, 1.56103895, 1.63721545, 1.09278414, 1.59103412,
       1.20833688, 1.11235941, 0.38393946, 1.67430993, 1.35601733])

In [ ]:
sub

array([ 0.39601037, -0.33260151, -0.06523454,  0.3697976 , -0.34104398,
        0.15808023,  0.25966342, -0.35751192, -0.3048509 , -0.20067173])

In [ ]:
div

array([1.99077174, 0.64871736, 0.92336393, 2.02297231, 0.64696667,
       1.30103163, 1.60904101, 0.03564298, 0.69193924, 0.74218136])

In [ ]:
mult

array([0.31804411, 0.58155471, 0.66905472, 0.26435673, 0.60376964,
       0.35877216, 0.29247959, 0.00489868, 0.67759492, 0.44962846])

In [ ]:
dot

4.2201537215349845

In [ ]:
# Statistic Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2, 7)
log = np.log(25)
exp = np.exp([2, 3])
mins = np.min(list1)
maxs = np.max(list2)

In [ ]:
sqrt

5.0

In [ ]:
ab

2

In [ ]:
power

128

In [ ]:
log

3.2188758248682006

In [ ]:
exp

array([ 7.3890561 , 20.08553692])

In [ ]:
mins

0.013213768872166187

In [ ]:
maxs

0.9895804143681881

In [11]:
data

array([[[0.0878162 , 0.86601353, 0.54729465, 0.90737194],
        [0.47781666, 0.85206039, 0.10925992, 0.02745276],
        [0.77755713, 0.0191249 , 0.82907258, 0.40342299]],

       [[0.77901071, 0.2538194 , 0.76743541, 0.70292923],
        [0.11290255, 0.73933179, 0.33463439, 0.36729466],
        [0.40398917, 0.38927956, 0.14102667, 0.64408237]]])

In [13]:
data[0][0][0] = 700
data

array([[[7.00000000e+02, 8.66013531e-01, 5.47294653e-01, 9.07371940e-01],
        [4.77816658e-01, 8.52060394e-01, 1.09259917e-01, 2.74527585e-02],
        [7.77557127e-01, 1.91248963e-02, 8.29072576e-01, 4.03422993e-01]],

       [[7.79010707e-01, 2.53819397e-01, 7.67435411e-01, 7.02929227e-01],
        [1.12902548e-01, 7.39331790e-01, 3.34634389e-01, 3.67294658e-01],
        [4.03989172e-01, 3.89279565e-01, 1.41026674e-01, 6.44082369e-01]]])

In [14]:
data.sort()
data

array([[[5.47294653e-01, 8.66013531e-01, 9.07371940e-01, 7.00000000e+02],
        [2.74527585e-02, 1.09259917e-01, 4.77816658e-01, 8.52060394e-01],
        [1.91248963e-02, 4.03422993e-01, 7.77557127e-01, 8.29072576e-01]],

       [[2.53819397e-01, 7.02929227e-01, 7.67435411e-01, 7.79010707e-01],
        [1.12902548e-01, 3.34634389e-01, 3.67294658e-01, 7.39331790e-01],
        [1.41026674e-01, 3.89279565e-01, 4.03989172e-01, 6.44082369e-01]]])

In [ ]:
print(data.shape)

(2, 3, 4)


In [ ]:
data = data.reshape((2, 2, -1))
data.shape

(2, 2, 6)

In [16]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3, 4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [17]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


In [18]:
np.delete(data, 0, axis=1)

array([[[0.02745276, 0.10925992, 0.47781666, 0.85206039],
        [0.0191249 , 0.40342299, 0.77755713, 0.82907258]],

       [[0.11290255, 0.33463439, 0.36729466, 0.73933179],
        [0.14102667, 0.38927956, 0.40398917, 0.64408237]]])

In [19]:
np.save("new array", data)

In [20]:
test = np.load("new array.npy")

In [21]:
test

array([[[5.47294653e-01, 8.66013531e-01, 9.07371940e-01, 7.00000000e+02],
        [2.74527585e-02, 1.09259917e-01, 4.77816658e-01, 8.52060394e-01],
        [1.91248963e-02, 4.03422993e-01, 7.77557127e-01, 8.29072576e-01]],

       [[2.53819397e-01, 7.02929227e-01, 7.67435411e-01, 7.79010707e-01],
        [1.12902548e-01, 3.34634389e-01, 3.67294658e-01, 7.39331790e-01],
        [1.41026674e-01, 3.89279565e-01, 4.03989172e-01, 6.44082369e-01]]])